# Generated by Django 6.1.1 on 2026-09-09 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_choice', models.CharField(choices=[('avatar-oak-leaf.png', 'Oak Leaf'), ('avatar-acorn.png', 'Acorn'), ('avatar-robin.png', 'Robin'), ('avatar-fox.png', 'Fox'), ('avatar-hedgehog.png', 'Hedgehog'), ('avatar-fern.png', 'Fern'), ('avatar-badger.png', 'Badger'), ('avatar-squirrel.png', 'Squirrel'), ('avatar-deer.png', 'Deer'), ('avatar-pinecone.png', 'Pinecone')], default='avatar-oak-leaf.png', max_length=40)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
