# Generated by Django 6.1.1 on 2026-09-09 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('tree_species', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='tree-reports/')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('what3words', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('PROTECTED', 'Protected'), ('RESOLVED', 'Resolved'), ('NEEDS_ATTENTION', 'Needs Attention')], db_index=True, default='ACTIVE', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='progress-updates/')),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('PROTECTED', 'Protected'), ('RESOLVED', 'Resolved'), ('NEEDS_ATTENTION', 'Needs Attention')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('tree_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='reports.treereport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
