# Generated by Django 6.1.1 on 2026-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treereport',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='treereport',
            name='region',
            field=models.CharField(blank=True, help_text='County, state, province or region.', max_length=120),
        ),
        migrations.AddField(
            model_name='treereport',
            name='town_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='treereport',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
