# Generated by Django 6.1.1 on 2026-09-11 10:07

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_treereport_country_treereport_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treereport',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
