"""
Django settings for the I-V Tree project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


# ---------------------------------------------------------
# Base directory and environment variables
# ---------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# ---------------------------------------------------------
# Security
# ---------------------------------------------------------

SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

DEBUG = os.getenv(
    'DEBUG',
    'False',
).lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        'ALLOWED_HOSTS',
        '127.0.0.1,localhost',
    ).split(',')
    if host.strip()
]


# ---------------------------------------------------------
# Application definition
# ---------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'accounts',
    'reports',
    'community',
    'support',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ---------------------------------------------------------
# Database
# ---------------------------------------------------------

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# ---------------------------------------------------------
# Password validation
# ---------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# ---------------------------------------------------------
# Internationalization
# ---------------------------------------------------------

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------
# Static and media files
# ---------------------------------------------------------

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------
# Authentication
# ---------------------------------------------------------

LOGIN_REDIRECT_URL = 'core:home'

LOGOUT_REDIRECT_URL = 'core:home'


# ---------------------------------------------------------
# Email
# ---------------------------------------------------------

MAILER_BACKEND = os.getenv(
    'MAILER_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)

MAILERS = {
    'default': {
        'BACKEND': MAILER_BACKEND,
    },
}

if MAILER_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    MAILERS['default']['OPTIONS'] = {
        'host': os.environ['EMAIL_HOST'],
        'port': int(os.getenv('EMAIL_PORT', '587')),
        'username': os.environ['EMAIL_HOST_USER'],
        'password': os.environ['EMAIL_HOST_PASSWORD'],
        'use_tls': (
            os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
        ),
        'timeout': 10,
    }

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    'I-V Tree <noreply@iv-tree.co.uk>',
)


# ---------------------------------------------------------
# External APIs
# ---------------------------------------------------------

GOOGLE_MAPS_API_KEY = os.getenv(
    'GOOGLE_MAPS_API_KEY',
    '',
)

GOOGLE_MAPS_MAP_ID = os.getenv(
    'GOOGLE_MAPS_MAP_ID',
    '',
)

WHAT3WORDS_API_KEY = os.getenv(
    'WHAT3WORDS_API_KEY',
    '',
)


# ---------------------------------------------------------
# Stripe
# ---------------------------------------------------------

STRIPE_PUBLIC_KEY = os.getenv(
    'STRIPE_PUBLIC_KEY',
    '',
)

STRIPE_SECRET_KEY = os.getenv(
    'STRIPE_SECRET_KEY',
    '',
)

STRIPE_WEBHOOK_SECRET = os.getenv(
    'STRIPE_WEBHOOK_SECRET',
    '',
)

STRIPE_CURRENCY = os.getenv(
    'STRIPE_CURRENCY',
    'gbp',
)


# ---------------------------------------------------------
# Country selector
# ---------------------------------------------------------

COUNTRIES_FIRST = [
    'GB',
]

COUNTRIES_FIRST_BREAK = '----------------'